services:
  db:
    # Postgres - https://hub.docker.com/_/postgres
    # postgres:14-alpine compatible with Cloud SQL Postgres 14
    image: postgres:14-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 15432:5432
    environment:
      POSTGRES_PASSWORD: postgres

volumes:
  db_data:
